# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d0cd0e20de7fed7fb0a159a052b7972675cf59c0f239fc4c6db96384e773533ab4ab5e980365cfeb431b3a9f6a80546360ac0c8288c5c30babb8840fb47741c4

test:
  secret_key_base: cfb0fb09814db53577330075e9e47a530bffd8abd9b9ec047859ef9ed413ed34cfd0bf7f9f74a3576308d53f675d35e86abd66c872aa7a6910aa73a3b350b390

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
